routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
*/

Route::resource('/', 'IndexController', [
                                        'only' => 'index',
                                        'names' => [
                                            'index' => 'home'
                                        ]
]);
Route::resource('/portfolios', 'PortfolioController', [
                                                        'parameters' => [
                                                            'portfolios' => 'alias'
                                                        ]
]);
Route::resource('/articles', 'ArticlesController', [
                                                        'parameters' => [
                                                            'articles' => 'alias'
                                                        ]
]);
Route::get('/articles/cat/{cat_alias?}', ['uses' => 'ArticlesController@index', 'as' => 'articlesCat']);
Route::resource('comment', 'CommentController', ['only' => ['store']]);

resources/views/pink/articleBar.blade.php
    <div class="widget-first widget recent-posts">
        <h3>{{ Lang::get('ru.latest_project') }}</h3>

        <div class="recent-post group">
            @if(!$portfolios->isEmpty())
                @foreach($portfolios as $portfolio)

                    <div class="hentry-post group">
                        <div class="thumb-img">
                            <img style="width: 55px" src="{{ asset(env('THEME')) }}/images/projects/{{ $portfolio->img->mini }}"
                                 alt="{{ $portfolio->title }}" title="{{ $portfolio->title }}" />
                        </div>
                        <div class="text">
                            <a href="{{ route('portfolios.show', ['alias' => $portfolio->alias]) }}"
                               title="{{ $portfolio->title }}!" class="title">{{ $portfolio->title }}</a>
                            <p>{{ str_limit($portfolio->text, 130) }}</p>
                            <a class="read-more"
                               href="article.{{ route('portfolios.show', ['alias' => $portfolio->alias]) }}">
                                &rarr; {{ Lang::get('ru.read_more') }}</a>
                        </div>
                    </div>

                @endforeach

            @endif



        </div>
    </div>

    @if(!$comments->isEmpty())
        <div class="widget-last widget recent-comments">
            <h3>{{ Lang::get('ru.latest_comments') }}</h3>
            <div class="recent-post recent-comments group">
                @foreach($comments as $comment)
                    <div class="the-post group">
                        <div class="avatar">
                            @set($hash, ($comment->email) ? md5($comment->email) : $comment->user->email)
<!--                            --><?php
//                                $hash = ($comment->email) ? md5($comment->email) : $comment->user->email;
//                            ?>
                            <img alt="" src="http://www.gravatar.com/avatar/{{$hash}}?d=mm&s=55"
                                 class="avatar" />
                        </div>
                        <span class="author"><strong><a href="#">{{ isset($comment->user) ? $comment->user->name : $comment->name }}</a></strong> in</span>
                        <a class="title" href="{{ route('articles.show', ['alias' =>$comment->article->alias]) }}">{{ $comment->article->alias }}</a>
                        <p class="comment">
                            {{ $comment->text }} <a class="goto" href="{{ route('articles.show', ['alias' =>$comment->article->alias]) }}">&#187;</a>
                        </p>
                    </div>
                @endforeach
            </div>
        </div>
    @endif

resources/views/pink/article_content.blade.php
<div id="content-single" class="content group">
    <div class="hentry hentry-post blog-big group ">
        <!-- post featured & title -->

        @if($article)
      <?php //dd(json_decode($article->img));?>
        <div class="thumbnail">
            <!-- post title -->
            <h1 class="post-title">{{ $article->title }}<!--<a href="article.html"></a>--></h1>
            <!-- post featured -->
            <div class="image-wrap">
                <img src="{{asset(env('THEME'))}}/images/articles/{{ $article->img->max }}"
                     alt="{{ $article->title }}" title="{{ $article->title }}" />
            </div>
            <p class="date">
                <span class="month">{{ $article->created_at->format('M') }}</span>
                <span class="day">{{ $article->created_at->format('d') }}</span>
            </p>
        </div>
        <!-- post meta -->
        <div class="meta group">
            <p class="author"><span>by <a href="#" title="Posts by {{ $article->user->name }}"
                                          rel="author">{{ $article->user->name }} </a></span></p>
            <p class="categories"><span>In:
                    <a href="{{ route('articlesCat', ['cat_alias' => $article->category->alias]) }}"
                       title="View all posts in {{ $article->category->title }}" rel="category tag">{{ $article->category->title }}</a></span></p>
            <p class="comments"><span><a href="#comments" title="Comment on This is the title of the first article. Enjoy it.">{{ count($article->comments) ? count($article->comments) : '0'}} {{ Lang::choice('ru.comments', count($article->comments)) }}</a></span></p>
        </div>
        <!-- post content -->
        <div class="the-content single group">
            <p>{!! $article->text !!}</p>
            <div class="socials">
                <h2>love it, share it!</h2>
                <a href="https://www.facebook.com/sharer.html?u=http%3A%2F%2Fyourinspirationtheme.com%2Fdemo%2Fpinkrio%2F2012%2F09%2F24%2Fthis-is-the-title-of-the-first-article-enjoy-it%2F&amp;t=This+is+the+title+of+the+first+article.+Enjoy+it." class="socials-small facebook-small" title="Facebook">facebook</a>
                <a href="https://twitter.com/share?url=http%3A%2F%2Fyourinspirationtheme.com%2Fdemo%2Fpinkrio%2F2012%2F09%2F24%2Fthis-is-the-title-of-the-first-article-enjoy-it%2F&amp;text=This+is+the+title+of+the+first+article.+Enjoy+it." class="socials-small twitter-small" title="Twitter">twitter</a>
                <a href="https://plusone.google.com/_/+1/confirm?hl=en&amp;url=http%3A%2F%2Fyourinspirationtheme.com%2Fdemo%2Fpinkrio%2F2012%2F09%2F24%2Fthis-is-the-title-of-the-first-article-enjoy-it%2F&amp;title=This+is+the+title+of+the+first+article.+Enjoy+it." class="socials-small google-small" title="Google">google</a>
                <a href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2Fyourinspirationtheme.com%2Fdemo%2Fpinkrio%2F2012%2F09%2F24%2Fthis-is-the-title-of-the-first-article-enjoy-it%2F&amp;media=http://yourinspirationtheme.com/demo/pinkrio/files/2012/09/00212.jpg&amp;description=Fusce+nec+accumsan+eros.+Aenean+ac+orci+a+magna+vestibulum+posuere+quis+nec+nisi.+Maecenas+rutrum+vehicula+condimentum.+Donec+volutpat+nisl+ac+mauris+consectetur+gravida.+Lorem+ipsum+dolor+sit+amet%2C+consectetur+adipiscing+elit.+Donec+vel+vulputate+nibh.+Pellentesque%5B...%5D" class="socials-small pinterest-small" title="Pinterest">pinterest</a>
                <a href="http://yourinspirationtheme.com/demo/pinkrio/2012/09/24/this-is-the-title-of-the-first-article-enjoy-it/" class="socials-small bookmark-small" title="This is the title of the first article. Enjoy it.">bookmark</a>
            </div>
        </div>
        <p class="tags">Tags: <a href="#" rel="tag">book</a>, <a href="#" rel="tag">css</a>, <a href="#" rel="tag">design</a>, <a href="#" rel="tag">inspiration</a></p>
        <div class="clear"></div>
    </div>
    <!-- START COMMENTS -->
    <div id="comments">
        <h3 id="comments-title">
            <span>{{ count($article->comments) }}</span> {{ Lang::choice('ru.comments', count($article->comments)) }}
        </h3>

        @if(count($article->comments) > 0)

        @set($com, $article->comments->groupBy('parent_id'))
        <ol class="commentlist group">
            @foreach($com as $key =>$comments)

                @if($key !== 0)
                    @break
                @endif
                @include(env('THEME').'.comment', ['items' => $comments])
            @endforeach


        </ol>
        @endif
        <!-- START TRACKBACK & PINGBACK -->
        <h2 id="trackbacks">Trackbacks and pingbacks</h2>
        <ol class="trackbacklist"></ol>
        <p><em>No trackback or pingback available for this article.</em></p>

        <!-- END TRACKBACK & PINGBACK -->
        <div id="respond">
            <h3 id="reply-title">Leave a <span>Reply</span> <small><a rel="nofollow" id="cancel-comment-reply-link" href="#respond" style="display:none;">Cancel reply</a></small></h3>
            <form action="{{ route('comment.store') }}" method="post" id="commentform">
                @if(!Auth::check())
                    <p class="comment-form-author"><label for="author">Name</label>
                        <input id="author" name="author" type="text" value="" size="30" aria-required="true" /></p>
                    <p class="comment-form-email"><label for="email">Email</label>
                        <input id="email" name="email" type="text" value="" size="30" aria-required="true" /></p>
                    <p class="comment-form-url"><label for="url">Website</label>
                        <input id="url" name="url" type="text" value="" size="30" /></p>
                @endif

                <p class="comment-form-comment"><label for="comment">Your comment</label><textarea id="comment" name="comment" cols="45" rows="8"></textarea></p>
                <div class="clear"></div>
                <p class="form-submit">

                    {{ csrf_field() }}
                    <input id="comment_post_id" type="hidden" name="comment_post_id" value="{{ $article->id }}"/>
                    <input id="comment_parent" type="hidden" name="comment_parent" value=""/>
                    <input name="submit" type="submit" id="submit" value="Post Comment" />
                </p>
            </form>
        </div>
        <!-- #respond -->
    </div>
    <!-- END COMMENTS -->

    @endif
</div>

resources/views/pink/articles.blade.php
@extends (env('THEME').'.layouts.site')

@section('navigation')
    {!! $navigation !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

@section('bar')
    {!! $rightBar !!}
@endsection

@section('footer')
    {!! $footer !!}
@endsection

resources/views/pink/articles_content.blade.php
    <div id="content-blog" class="content group">
        @if($articles)

            @foreach($articles as $article)

                <div class="sticky hentry hentry-post blog-big group">
                    <!-- post featured & title -->
                    <div class="thumbnail">
                        <!-- post title -->
                        <h2 class="post-title"><a href="{{ route('articles.show', ['alias' =>$article->alias]) }}">
                                {{ $article->title }}</a></h2>
                        <!-- post featured -->
                        <div class="image-wrap">
                            <img src="{{ asset(env('THEME')) }}/images/articles/{{ $article->img->max }}"
                                 alt="{{ $article->title }}" title="{{ $article->title }}" />
                        </div>
                        <p class="date">
                            <span class="month">{{ $article->created_at->format('F') }}</span>
                            <span class="day">{{ $article->created_at->format('j') }}</span>
                        </p>
                    </div>
                    <!-- post meta -->
                    <div class="meta group">
                        <p class="author"><span>by
                            <a href="#" title="Posts by {{ $article->user->name }}" rel="author">
                                {{ $article->user->name }}</a></span></p>

                        <p class="categories"><span>In:
                            <a href="{{ route('articlesCat', ['cat_alias' => $article->category->alias]) }}"
                               title="View all posts in {{ $article->category->title }}"
                               rel="category tag">{{ $article->category->title }}</a>

                        <p class="comments"><span>
                            <a href="{{ route('articles.show', ['alias' =>$article->alias]) }}#respond"
                               title="Comment on Section shortcodes &amp; sticky posts!">
                                {{ count($article->comments) ? count($article->comments) : '0' }}
                                {{ Lang::choice('ru.comments', count($article->comments)) }}</a></span></p>
                    </div>
                    <!-- post content -->
                    <div class="the-content group">
                        {!!  $article->desc !!}
                        <p><a href="{{ route('articles.show', ['alias' => $article->alias]) }}"
                              class="btn   btn-beetle-bus-goes-jamba-juice-4 btn-more-link">
                                {{ Lang::get('ru.read_more') }}</a></p>
                    </div>
                    <div class="clear"></div>
                </div>

            @endforeach


            <div class="general-pagination group">
                @if($articles->lastPage() > 1)
                    @if($articles->currentPage() != 1)
                        <a href="{{ $articles->url($articles->currentPage() - 1) }}">
                            {{ Lang::get('pagination.previous') }}</a>

                    @endif

                    @for($i = 1; $i <= $articles->lastPage(); $i++ )
                        @if($articles->currentPage() == $i)
                            <a class="selected disabled">{{ $i }}</a>
                        @else
                                <a href="{{ $articles->url($i) }}">{{ $i }}</a>
                        @endif
                    @endfor

                    @if($articles->currentPage() !== $articles->lastPage())
                            <a href="{{ $articles->url($articles->currentPage() + 1) }}">
                                {{ Lang::get('pagination.next') }}</a>

                    @endif

                @endif


            </div>
        @else
            {{ Lang::get('ru.articles_no')}}

        @endif
    </div>

resources/views/pink/comment.blade.php
@foreach($items as $item)
<li id="li-comment-{{$item->id}}" class="comment even {{($item->user_id == $article->user_id) ? 'bypostauthor odd' : '' }}">
    <div id="{{ $item->id }}" class="comment-container">
        <div class="comment-author vcard">
            @set($hash, isset($item->email) ? md5($item->email) : md5($item->user->email))
            <img alt="" src="https://www.gravatar.com/avatar/{{$hash}}?d=mm&s=75" class="avatar" height="75" width="75" />
            <cite class="fn">{{ $item->user->name or $item->name }}</cite>
        </div>
        <!-- .comment-author .vcard -->
        <div class="comment-meta commentmetadata">
            <div class="intro">
                <div class="commentDate">
                    <p>{{ is_object($item->created_at) ? $item->created_at->format('F d, Y \a\t H:i') : '' }}</p>
                </div>
                <div class="commentNumber">#&nbsp;</div>
            </div>
            <div class="comment-body">
                <p>{{ $item->text }}</p>
            </div>
            <div class="reply group">
                <a class="comment-reply-link" href="#respond" onclick="return
                addComment.moveForm(&quot;comment-{{ $item->id }}&quot;, &quot;{{ $item->id }}&quot;, &quot;respond&quot;, &quot;{{ $item->article_id }}&quot;)">{{ Lang::get('ru.replay') }}</a>
            </div>
            <!-- .reply -->
        </div>
        <!-- .comment-meta .commentmetadata -->
    </div>
    <!-- #comment-##  -->
    @if(isset($com[$item->id]))
        <ul class="children" >
            @include(env('THEME').'.comment', ['items' => $com[$item->id]])
        </ul>
    @endif

</li>
@endforeach

resources/views/pink/content.blade.php
@if($portfolios && count($portfolios) > 0)
<div id="content-home" class="content group">
    <div class="hentry group">
        <div class="section portfolio">

            <h3 class="title">{{ trans('ru.latest_projects') }}</h3>

            @foreach($portfolios as $key => $item)

                @if($key == 0)
                    <div class="hentry work group portfolio-sticky portfolio-full-description">
                        <div class="work-thumbnail">
                            <a class="thumb">
                                <img src="{{asset(env('THEME'))}}/images/projects/{{ $item->img->max }}" alt="0081" title="0081" /></a>
                            <div class="work-overlay">
                                <h3><a href="{{ route('portfolios.show',
                                ['alias' => $item->alias]) }}">{{$item->title}}</a></h3>

                                <p class="work-overlay-categories">
                                    <img src="{{asset(env('THEME'))}}/images/categories.png" alt="Categories" /> in:
                                    <a href="#">{{$item->filter->title}}</a></p>
                            </div>
                        </div>
                        <div class="work-description">
                            <h2><a href="{{ route('portfolios.show',
                                ['alias' => $item->alias]) }}">{{$item->title}}</a></h2>
                            <p class="work-categories">in: <a href="#">{{$item->filter->title}}</a></p>
                            <p>{{ str_limit($item->text, 200) }}</p>
                                <a href="{{ route('portfolios.show',
                                ['alias' => $item->alias]) }}" class="read-more">|| Read more</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                    @continue
                @endif

            @if($key == 1)
            <div class="portfolio-projects">
            @endif
                <div class="related_project {{ ($key == 4) ? 'related_project_last': '' }}">
                    <div class="overlay_a related_img">
                        <div class="overlay_wrapper">
                            <img src="{{asset(env('THEME'))}}/images/projects/{{$item->img->mini}}" alt="0061" title="0061" />
                            <div class="overlay">
                                <a class="overlay_img"
                                   href="{{asset(env('THEME'))}}/images/projects/{{$item->img->path}}" rel="lightbox" title=""></a>
                                <a class="overlay_project" href="{{ route('portfolios.show',
                                ['alias' => $item->alias]) }}"></a>
                                <span class="overlay_title">{{ $item->title }}</span>
                            </div>
                        </div>
                    </div>
                    <h4><a href="{{ route('portfolios.show',
                                ['alias' => $item->alias]) }}">{{ $item->title }}</a></h4>
                    <p>{{ str_limit($item->text, 200) }}</p>
                </div>
            @endforeach
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <!-- START COMMENTS -->
    <div id="comments">
    </div>
    <!-- END COMMENTS -->
</div>
@endif

resources/views/pink/customMenuItems.blade.php
@foreach($items as $item)
    <li {{ (URL::current() == $item->url()) ? "class=active" : ''}}>
        <a href="{{ $item->url() }}">{{ $item->title }}</a>
        @if($item->hasChildren())
            <ul class="sub-menu">
                @include(env('THEME').'.customMenuItems', ['items' => $item->children()])
            </ul>
        @endif
    </li>

@endforeach

resources/views/pink/footer.blade.php
<div id="copyright">
    <div class="inner group">
        <div class="left">
            <a href="https://www.facebook.com/ruslan.pomazan" target="_blank"><strong>Developed by Ruslan Pomazan
                </strong></a>
        </div>
        <div class="right">
            <a href="#" class="socials-small facebook-small" title="Facebook">facebook</a>
            <a href="#" class="socials-small rss-small" title="Rss">rss</a>
            <a href="#" class="socials-small twitter-small" title="Twitter">twitter</a>
            <a href="#" class="socials-small flickr-small" title="Flickr">flickr</a>
            <a href="#" class="socials-small skype-small" title="Skype">skype</a>
            <a href="#" class="socials-small google-small" title="Google">google</a>
            <a href="#" class="socials-small pinterest-small" title="Pinterest">pinterest</a>
        </div>
    </div>
</div>

resources/views/pink/index.blade.php
@extends (env('THEME').'.layouts.site')

@section('navigation')
    {!! $navigation !!}
@endsection

@section('slider')
    {!! $sliders !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

@section('bar')
    {!! $rightBar !!}
@endsection

@section('footer')
    {!! $footer !!}
@endsection

resources/views/pink/indexBar.blade.php
    <div class="widget-first widget recent-posts">

        @if($articles)
            <h3>{{ trans('ru.from_blog') }}</h3>
            <div class="recent-post group">
                @foreach($articles as $article)
                    <div class="hentry-post group">
                        <div class="thumb-img"><img src="{{asset(env('THEME'))}}/images/articles/{{$article->img->mini}}" alt="001" title="001" /></div>
                        <div class="text">
                            <a href="{{ route('articles.show',
                                ['alias' => $article->alias]) }}" title="Section shortcodes &amp; sticky posts!" class="title">{{$article->title}}</a>
                            <p class="post-date">{{$article->created_at->format('F d, Y')}}</p>
                        </div>
                    </div>
                @endforeach

            </div>
        @endif


    </div>

    <div class="widget-last widget text-image">
        <h3>Customer support</h3>
        <div class="text-image" style="text-align:left"><img src="{{asset(env('THEME'))}}/images/callus.gif" alt="Customer support" /></div>
        <p>Proin porttitor dolor eu nibh lacinia at ultrices lorem venenatis. Sed volutpat scelerisque vulputate. </p>
    </div>

resources/views/pink/navigation.blade.php
@if($menu)
    <div class="menu classic">
        <ul id="nav" class="menu">
            @include(env('THEME').'.customMenuItems', ['items' => $menu->roots()])
        </ul>
    </div>
@endif

resources/views/pink/rightBar.blade.php
<div class="sidebar group">
    {!! $content_rightBar !!}
</div>

resources/views/pink/slider.blade.php
@if(count($sliders) > 0)

<div id="slider-cycle" class="slider cycle no-responsive slider_cycle group" style="height:485px;">
    <ul class="slider">


        @set($i, 0)
        @foreach($sliders as $slider)

            <li>
                <div class="slide-holder" style="background:  url('{{asset(env('THEME'))}}/images/{{ $slider->img }}') no-repeat center center" style="height:483px;">
                    <div class="slide-content-holder inner" style="height:483px;">

                        @if($i%2 == 0)
                            <div class="slide-content-holder-content" style="position: absolute; top:30px;right:650px;">
                        @else
                            <div class="slide-content-holder-content" style="position: absolute; top:80px;left:500px;">
                        @endif
                                <div class="slide-title">
                                    {!! $slider->title !!}
                                </div>
                                <div class="slide-content" style="color:#fff">
                                    <p>{!! $slider->text !!}</p>
                                </div>
                            </div>
                    </div>
                </div>
            </li>

        @set($i, $i+1)
        @endforeach

        </ul>

        <div id="yit-widget-area" class="group">
            <div class="yit-widget-content inner group">
                <div class="widget-first yit-widget widget col1_4 one-fourth col widget-icon-text group">
                    <img class="icon-img" src="{{asset(env('THEME'))}}/images/icons/cloud.jpg" alt="" />
                    <h3>Great Design</h3>
                    <p>A widgetized area: add shorcodes, text, icons and more.</p>
            </div>
            <div class="yit-widget widget col1_4 one-fourth col widget-last-post group">
                <img class="icon-img" src="{{asset(env('THEME'))}}/images/icons/blog1.png" alt="" />
                <div>
                    <h3><a class="text-color" href="#" title="">Blog news</a></h3>
                    <p>Section shortcodes &amp; sticky posts! <a href="article.html"> | more →</a></p>
                </div>
            </div>
            <div class="widget-last yit-widget widget col1_4 one-fourth col yit_text_quote">
                <blockquote class="text-quote-quote">“Anyone who has never made a mistake has never tried anything new.”</blockquote>
                <cite class="text-quote-author">Albert Einstein</cite>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function($){

        var     yit_slider_cycle_fx = 'easing',
            yit_slider_cycle_speed = 800,
            yit_slider_cycle_timeout = 3000,
            yit_slider_cycle_directionNav = true,
            yit_slider_cycle_directionNavHide = true,
            yit_slider_cycle_autoplay = true;

        var yit_widget_area_position = function(){
            $('#yit-widget-area').css({ top: 33 - $('#yit-widget-area').height() });
        };
        $(window).resize(yit_widget_area_position);
        yit_widget_area_position();

        if( $.browser.msie && parseInt($.browser.version.substr(0,1),10) <= '8' ) {
            $('#slider-cycle ul.slider').anythingSlider({
                expand              : true,
                startStopped        : false,
                buildArrows         : yit_slider_cycle_directionNav,
                buildNavigation     : false,
                buildStartStop      : false,
                delay               : yit_slider_cycle_timeout,
                animationTime       : yit_slider_cycle_speed,
                easing              : yit_slider_cycle_fx,
                autoPlay            : yit_slider_cycle_autoplay ? true : false,
                pauseOnHover        : true,
                toggleArrows        : false,
                resizeContents      : true
            });
        } else {
            $('#slider-cycle ul.slider').anythingSlider({
                expand              : true,
                startStopped        : false,
                buildArrows         : yit_slider_cycle_directionNav,
                buildNavigation     : false,
                buildStartStop      : false,
                delay               : yit_slider_cycle_timeout,
                animationTime       : yit_slider_cycle_speed,
                easing              : yit_slider_cycle_fx,
                autoPlay            : yit_slider_cycle_autoplay ? true : false,
                pauseOnHover        : true,
                toggleArrows        : yit_slider_cycle_directionNavHide ? true : false,
                onSlideComplete     : function(slider){},
                resizeContents      : true,
                onSlideBegin        : function(slider) {},
                onSlideComplete     : function(slider) {}
            });

        }
    });
</script>
<div class="mobile-slider">
    <div class="slider fixed-image inner"><img src="{{asset(env('THEME'))}}/images/slider-cycle/cycle-fixed.jpg" alt="" /></div>
</div>
@endif